version: 1.7.0.{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017 
      TOOLS: "MSVC"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TOOLS: "MinGW"

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

install:  
  - ps: if($env:build_platform -eq 'x64') {
          $env:vcvar_arg = 'x86_amd64';
          $env:ARCH = 'x64';
          $env:MINGWPATH='C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw32\bin\'
        }
        else {
          $env:vcvar_arg = 'x86';
          $env:ARCH = 'Win32';  
          $env:MINGWPATH='C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin\'
        }

build_script:
  - if [%TOOLS%]==[MSVC] "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
  - if [%TOOLS%]==[MSVC] set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;%PATH%
  - if [%TOOLS%]==[MinGW] SET PATH=%MINGWPATH%;%PATH%
  - echo %PATH%
  - if [%TOOLS%]==[MinGW] dir %MINGWPATH%
  - if [%TOOLS%]==[MSVC]  dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\"
  - if [%TOOLS%]==[MSVC] "build-all-msvc.bat" %CONFIGURATION% %ARCH%
  - if [%TOOLS%]==[MinGW] "build-all-mingw.bat" %CONFIGURATION%
